#!/usr/bin/env python
"""isort:skip_file
"""
import os
import sys; sys.path.append(os.path.join(os.path.abspath(os.path.dirname(__file__)), ".."))  # noqa

import readline
from code import InteractiveConsole

from molten.contrib.sqlalchemy import Session

from index import create_app

app = create_app()
resolver = app.injector.get_resolver()


@resolver.resolve
def get_session(session: Session):
    return session


helpers = {
    "app": app,
    "resolver": resolver,
    "session": get_session(),
}

readline.parse_and_bind("tab: complete")
interpreter = InteractiveConsole(helpers)
interpreter.interact(f"""\
Instances in scope: {", ".join(helpers)}.
""", "")